apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tetris

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: svishal25/tetris
    newTag: local
