name: Release - Scan and Push Image

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy config scan (Dockerfile best practices)
        uses: aquasecurity/trivy-action@master
        with:
            scan-type: 'config'
            scan-ref: '.'
            exit-code: '1'
            severity: 'CRITICAL,HIGH'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image locally (not pushed yet)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: tetris:scan-candidate

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: tetris:scan-candidate
          format: table
          exit-code: '1'          # fails this job (and blocks "push") if matches are found
          severity: 'CRITICAL,HIGH'

  push:
    needs: build               # will not run at all unless "build" (including the Trivy step) succeeded
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      #Included to support multi-arch builds on non-x86 runners 
      #(e.g. Apple Silicon)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # This is will push the same image to multiple platforms 
          #(e.g. linux/amd64 and linux/arm64) and 
          #tag it with the GitHub release tag, the commit SHA, and "latest"
          platforms: linux/amd64,linux/arm64
          tags: |
            svishal25/tetris:${{ github.ref_name }}
            svishal25/tetris:${{ github.sha }}
            svishal25/tetris:latest